module.exports = {
  siteMetadata: {
    title: "Gatsby Starter for Refcome",
    description: "Generated by boilerplate",
    author: "@refcome",
  },
  plugins: [
    `gatsby-plugin-typescript`,
    `gatsby-plugin-react-helmet`,
    `gatsby-plugin-styled-jsx`,
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `images`,
        path: `${__dirname}/src/images`,
      },
    },
    `gatsby-transformer-sharp`,
    `gatsby-plugin-sharp`,
    {
      resolve: "gatsby-plugin-svgr",
      options: {
        include: /inline_svg/,
      },
    },
  ],
}
